name: "Zoraxy_Home_Assistant"
version: "1.0.0"
slug: "zoraxy"
description: "Zoraxy add-on for Home Assistant"
url: "https://github.com/Jefedi/zoraxy-ha-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
host_network: true
init: false
